name: feliz_aniversario
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^7.2.1
  http: ^1.1.0 
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  html: ^0.15.4
  infinite_scroll_pagination: ^4.0.0
  flutter_share_me: ^1.4.0
  flutter_native_splash: ^2.3.7
  icons_launcher: ^2.1.6
  logger: ^2.3.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true




